-- chess.game definition

CREATE TABLE `game` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `event` varchar(300) DEFAULT NULL,
  `site` varchar(300) DEFAULT NULL,
  `game_date` date DEFAULT NULL,
  `round` varchar(50) DEFAULT NULL,
  `result` int(11) DEFAULT NULL COMMENT '1 white wins\n2 black wins\n3 draw\n4 otherwise',
  `event_date` date DEFAULT NULL,
  `event_sponsor` varchar(300) DEFAULT NULL,
  `section` varchar(100) DEFAULT NULL,
  `stage` varchar(100) DEFAULT NULL,
  `board` int(11) DEFAULT NULL,
  `opening` varchar(100) DEFAULT NULL,
  `variation` varchar(100) DEFAULT NULL,
  `subvariation` varchar(100) DEFAULT NULL,
  `eco` varchar(100) DEFAULT NULL,
  `nic` varchar(100) DEFAULT NULL,
  `game_time` varchar(10) DEFAULT NULL,
  `game_utc_date` varchar(20) DEFAULT NULL,
  `game_utc_time` varchar(20) DEFAULT NULL,
  `time_control` varchar(300) DEFAULT NULL,
  `setup` int(11) DEFAULT NULL,
  `fen` varchar(100) DEFAULT NULL,
  `termination` varchar(100) DEFAULT NULL,
  `annotator` varchar(300) DEFAULT NULL,
  `mode` varchar(100) DEFAULT NULL,
  `plycount` int(11) DEFAULT NULL,
  `white_player_id` bigint(20) DEFAULT NULL,
  `black_player_id` bigint(20) DEFAULT NULL,
  `import_date` date DEFAULT NULL,
  `source` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `game_id_IDX` (`id`) USING BTREE,
  KEY `game_white_player_id_IDX` (`white_player_id`) USING BTREE,
  KEY `game_black_player_id_IDX` (`black_player_id`) USING BTREE,
  CONSTRAINT `game_player_FK` FOREIGN KEY (`white_player_id`) REFERENCES `player` (`id`),
  CONSTRAINT `game_player_FK_1` FOREIGN KEY (`black_player_id`) REFERENCES `player` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=138017 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;