CREATE USER 'chess_user'@'localhost' IDENTIFIED BY '***';
GRANT USAGE ON *.* TO 'chess_user'@'localhost';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `chess`.* TO 'chess_user'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'chess_user'@'localhost';
SHOW CREATE USER 'chess_user'@'localhost';